// this file is automatically generated, and git-ignored.
var Config = {
    lcp: {url: 'http://localhost:8989', user:'name', password: 'pass'},
    lsd: {url: 'http://localhost:8990', user:'name', password: 'pass'}
}
