// This file is automatically generated, and git-ignored.
// To ignore your local changes, use:
// git update-index --assume-unchanged lcpserver/manage/config.js

var Config = {
    lcp: {url: 'http://127.0.0.1:8081', user:'badu', password: 'hello'},
    lsd: {url: 'http://127.0.0.1:8082', user:'badu', password: 'hello'}
}
