// This file is automatically generated, and git-ignored.
// To ignore your local changes, use:
// git update-index --assume-unchanged lcpserver/manage/config.js

var Config = {
    lcp: {url: 'http://localhost:8989', user:'Stefaan', password: 'testlcpserver'},
    lsd: {url: 'http://localhost:8990', user:'Stefaan', password: 'testlcpserver'}
}
