// This file is automatically generated, and git-ignored.
// To ignore your local changes, use:
// git update-index --assume-unchanged frontend/manage/config.js

var Config = {
    lcp: {url: 'http://192.168.1.93:8989', user:'username', password: 'pass'},
    lsd: {url: 'http://192.168.1.93:8990', user:'username', password: 'pass'}
}
