steps:
  # Docker Build
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/libuserkey.a', '/workspace/libuserkey.a']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/userkey.h', '/workspace/userkey.h']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/user_key.go', '/workspace/user_key.go']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/cert-edrlab.pem', '/workspace/cert-edrlab.pem']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://lcpserver-build-prod/privkey-edrlab.pem', '/workspace/privkey-edrlab.pem']
  - name: 'gcr.io/cloud-builders/docker'

    args: ['build', '-t', 
    'europe-west1-docker.pkg.dev/lcpserver-1/lcp-server-build/readium-lcp-server-build-prod:latest', 
    '-f', 'docker/Dockerfile',
    '--build-arg', 'LIBUSERKEY_PATH=/libuserkey.a',
    '--build-arg', 'USERKEYH_PATH=/userkey.h',
    '--build-arg', 'USERKEYGO_PATH=/user_key.go',
    '--build-arg', 'BUILD_PROD=true',
    '--build-arg', 'PRIVATE_KEY_PATH=/privkey-edrlab.pem',
    '--build-arg', 'CERTIFICATE_PATH=/cert-edrlab.pem',
    '--build-arg', 'PROFILE=1.0',
    '.']

    # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
    'europe-west1-docker.pkg.dev/lcpserver-1/lcp-server-build/readium-lcp-server-build-prod:latest']

timeout: 3600s
