import { Injectable }   from '@angular/core';
import { Http, Headers }    from '@angular/http';

import 'rxjs/add/operator/toPromise';

import { DashboardInfo, DashboardBestSeller}  from './dashboardInfo';

import { CrudService }  from '../crud/crud.service';

declare var Config: any; //  this comes from the autogenerated config.js file

@Injectable()
export class DashboardService{
    private masterFileListUrl: string;
    private http:Http;
    private baseUrl: string;
    defaultHttpHeaders = new Headers({'Content-Type': 'application/json'});
    

    constructor (http: Http) {
        this.http = http;
        this.baseUrl = Config.frontend.url;
        this.masterFileListUrl = Config.frontend.url + '/api/v1/repositories/master-files';
    }


    decode(jsonObj: any): DashboardInfo {
        return {
            publicationCount: jsonObj.publicationCount,
            userCount: jsonObj.userCount,
            buyCount: jsonObj.buyCount,
            loanCount: jsonObj.loanCount
        }
    }

    get(): Promise<DashboardInfo> {
        var self = this
        return this.http
            .get(
                this.baseUrl + "/dashboardInfos",
                { headers: this.defaultHttpHeaders })
            .toPromise()
            .then(function (response) {
                let jsonObj = response.json();
                return self.decode(jsonObj);
            })
            .catch(this.handleError);
    }

    getBestSeller(): Promise<DashboardBestSeller[]> {
        var self = this
        return this.http
            .get(
                this.baseUrl + "/dashboardBestSellers",
                { headers: this.defaultHttpHeaders })
            .toPromise()
            .then(function (response) {
                if (response.ok) {
                    let items: DashboardBestSeller[] = [];

                    for (let jsonObj of response.json()) {
                        items.push(jsonObj);
                    }

                    return items;
                } else {
                    throw 'Error creating user ' + response.text;
                }
            })
            .catch(this.handleError);
    }

    protected handleError(error: any): Promise<any> {
        console.error('An error occurred', error);
        return Promise.reject(error.message || error);
    }
}
