
	// This file is automatically generated, and git-ignored.
	// To ignore your local changes, use:
	// git update-index --assume-unchanged frontend/manage/config.js
	window.Config = {
	frontend: {url: 'http://127.0.0.1:80' },
	lcp: {url: 'http://127.0.0.1:8081', user: 'badu', password: 'hello'},
	lsd: {url: 'http://127.0.0.1:8082', user: 'badu', password: 'hello'}
}